---
driver_plugin: vagrant
driver:
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver:
    box: ubuntu/precise64
    network:
      - [ 'private_network', { ip: '33.33.33.10' } ]

- name: ubuntu-14.04
  driver:
    box: ubuntu/trusty64
    network:
      - [ 'private_network', { ip: '33.33.33.13' } ]

- name: ubuntu-16.04
  driver:
    box: ubuntu/xenial64
    network:
      - [ 'private_network', { ip: '33.33.33.11' } ]

- name: centos-6.8
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.12' } ]

suites:
- name: default
  run_list: ['recipe[gocd]']
