##########################################################################
# Copyright 2017 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

platforms:
- name: centos-6
- name: centos-7
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
- name: default
  run_list:
  - recipe[gocd]
  attributes:
    gocd:
      server:
        max_mem: '2048m'
        min_mem: '512m'
      agent:
        count: 2 # good test for agent lwrp
        autoregister:
          key: 'auto-register-key'
          environments: ['staging', 'perf']
          resources: ['foo', 'bar', 'baz']
          hostname: 'example-host'
- name: package_file
  run_list:
  - recipe[gocd]
  attributes:
    gocd:
      install_method: 'package_file'
      server:
        max_mem: '2048m'
        min_mem: '512m'
      agent:
        autoregister:
          key: 'auto-register-key'
          environments: ['staging', 'perf']
          resources: ['foo', 'bar', 'baz']
          hostname: 'example-host'
