---
driver_plugin: vagrant
driver:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.10' } ]
- name: ubuntu-13.10
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.11' } ]
- name: centos-6.4
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.12' } ]

suites:
- name: default
  run_list: ['recipe[go]']
- name: custom_agent_resources
  run_list: ['recipe[go::agent]']
  attributes: {"go":{"agent":{"auto_register_resources":["a", "b", "c"]}}}
  excludes:
    - centos-6.4
- name: agent-v13
  run_list: ['recipe[go::agent_linux]']
  attributes: 
    go:
      version: '13.1.1-16714'
      apt_repo: "http://download01.thoughtworks.com/go/debian"
      apt_components": 
        - 'contrib/'